version: '3.9'

services:
  db:
    image: postgres:15
    container_name: mini-erp-db
    environment:
      POSTGRES_DB: mini-erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mini-erp"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: mini-erp-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mini-erp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
    ports:
      - "8080:8080"
